{% set version = "0.6.0" %}

package:
  name: jupyter-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-cache/jupyter-cache-{{ version }}.tar.gz
  sha256: 4f6ef31f992cfee6f0efc7ce070267f5ab57fe3ad7e39566d4f1a9719b005e35

build:
  number: 0
  noarch: python
  entry_points:
    - jcache = jupyter_cache.cli.commands.cmd_main:jcache
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core >=3.4,<4
    - pip
    - python >=3.8
  run:
    - attrs
    - click
    - importlib-metadata
    - nbclient >=0.2,<0.8
    - nbformat
    - python >=3.8
    - pyyaml
    - sqlalchemy >=1.3.12,<3
    - tabulate

test:
  imports:
    - jupyter_cache
    - jupyter_cache.cache
  commands:
    - pip check
    - jcache --help
  requires:
    - pip

about:
  home: https://github.com/ExecutableBookProject/jupyter-cache
  summary: A defined interface for working with a cache of jupyter notebooks.
  license: MIT
  license_file: LICENSE
  doc_url: https://jupyter-cache.readthedocs.io

extra:
  recipe-maintainers:
    - anirrudh
    - conda-forge/jupyter-book
